CREATE EXTENSION IF NOT EXISTS http;
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

ALTER DATABASE postgres SET timezone TO 'Africa/Cairo';

CREATE TABLE IF NOT EXISTS public.user_settings (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id text NOT NULL UNIQUE, 
    user_supabase_url text,
    user_supabase_key text,
    amazon_access_key text,
    amazon_secret_key text,
    amazon_partner_tag text,
    tg_bot_token text,
    tg_chat_id text,
    tg_admin_id text,
    fb_page_id text,
    fb_access_token text,
    ai_api_key text,
    post_template text, 
    post_footer text,
    updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.products (
    asin text PRIMARY KEY,
    user_id text,             
    title text,
    image text,
    price float8,
    old_price float8,
    discount int4,
    extra_payment_discount int4 DEFAULT 0,
    template_id int4 DEFAULT 0,
    affiliate_link text,
    message_id int8,           
    fb_post_id text,           
    is_available boolean DEFAULT true,
    disable_notification boolean DEFAULT false, 
    published_at text,        
    scheduled_at timestamptz,
    custom_template text,
    footer_text text,
    last_update timestamptz DEFAULT now()
);

INSERT INTO storage.buckets (id, name, public)
VALUES ('banners', 'banners', true)
ON CONFLICT (id) DO NOTHING;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access') THEN
        CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'banners');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Service Role Full Access') THEN
        CREATE POLICY "Service Role Full Access" ON storage.objects FOR ALL TO service_role USING (bucket_id = 'banners') WITH CHECK (bucket_id = 'banners');
    END IF;
END $$;


CREATE OR REPLACE FUNCTION handle_scheduled_publishing()
RETURNS void AS $$
DECLARE
    item RECORD;
    set RECORD;
    final_text text;
    price_section text;
    final_price int;
    old_price_val int;
    time_part text;
    tg_result jsonb;
    fb_result jsonb;
    fb_clean_text text;
    real_tg_token text;
    real_fb_token text;
    v_tg_msg_id int8;
    v_fb_post_id text;
    banner_data jsonb;
    final_image_url text;
BEGIN
    PERFORM set_config('http.timeout_msec', '30000', true);

    FOR item IN
        SELECT * FROM products
        WHERE published_at IS NULL
        AND scheduled_at <= (NOW() AT TIME ZONE 'Africa/Cairo')
        ORDER BY scheduled_at ASC 
        LIMIT 1 
        FOR UPDATE SKIP LOCKED
    LOOP
        v_tg_msg_id := NULL;
        v_fb_post_id := NULL;

        SELECT * INTO set FROM user_settings WHERE device_id = item.user_id LIMIT 1;
        IF set IS NULL THEN 
            RAISE NOTICE 'No settings found for device_id: %', item.user_id;
            CONTINUE; 
        END IF;

        real_tg_token := set.tg_bot_token;
        real_fb_token := set.fb_access_token;

        IF item.price IS NULL OR item.price = 0 THEN
            RAISE NOTICE 'Price is 0 for ASIN: %, skipping for now', item.asin;
            CONTINUE;
        END IF;

        final_image_url := item.image;

        IF COALESCE(item.template_id, 0) > 0 THEN
            BEGIN
                SELECT content::jsonb INTO banner_data FROM http_post(
                    'https://{{PROJECT_URL}}/functions/v1/generate-banner',
                    jsonb_build_object(
                        'asin', item.asin,
                        'price', item.price,
                        'image', item.image,
                        'discount', item.discount,
                        'template', CASE WHEN item.template_id = 1 THEN 'blue' WHEN item.template_id = 2 THEN 'orange' ELSE 'default' END
                    )::text,
                    'application/json'
                );
                IF banner_data->>'banner_url' IS NOT NULL AND banner_data->>'banner_url' <> '' THEN
                    final_image_url := banner_data->>'banner_url';
                END IF;
            EXCEPTION WHEN OTHERS THEN
                RAISE NOTICE 'Banner failed for ASIN: %, using original image', item.asin;
            END;
        END IF;

        SELECT TO_CHAR(NOW() AT TIME ZONE 'Africa/Cairo', 'HH12:MI ') ||
        CASE WHEN TO_CHAR(NOW() AT TIME ZONE 'Africa/Cairo', 'AM') = 'AM' THEN 'ص' ELSE 'م' END INTO time_part;

        final_price := FLOOR(item.price * (1 - (COALESCE(item.extra_payment_discount, 0)::float / 100)));
        old_price_val := FLOOR(COALESCE(item.old_price, 0));

        IF COALESCE(item.template_id, 0) = 3 AND item.custom_template IS NOT NULL THEN
            final_text := item.custom_template;
            final_text := replace(final_text, '{{TITLE}}', COALESCE(item.title, ''));
            final_text := replace(final_text, '{{PRICE}}', final_price::text || ' ج');
            final_text := replace(final_text, '{{OLD_PRICE}}', old_price_val::text || ' ج');
            final_text := replace(final_text, '{{LINK}}', COALESCE(item.affiliate_link, ''));
            
            IF item.footer_text IS NOT NULL THEN
                final_text := replace(final_text, '{{FOOTER}}', item.footer_text);
            ELSE
                final_text := replace(final_text, '{{FOOTER}}', '');
            END IF;
        ELSE
            CASE COALESCE(item.template_id, 0)
                WHEN 1 THEN
                    final_text := '<b>' || item.title || '</b>' || ' بسعر <b>' || final_price || 'ج</b>';
                    IF old_price_val > final_price THEN final_text := final_text || ' بدلاً من <s>' || old_price_val || 'ج</s>'; END IF;
                    final_text := final_text || chr(10) || chr(10) || 'لينك العرض : ' || item.affiliate_link;
                WHEN 2 THEN
                    final_text := '💎 <b>' || item.title || '</b>' || chr(10) || chr(10) ||
                    '🏷️ السعر الآن: <b>' || final_price || ' جنيه فقط</b>' || chr(10) || chr(10) ||
                    'لينك العرض : ' || item.affiliate_link;
                ELSE
                    IF (item.discount > 0 AND item.extra_payment_discount > 0) THEN
                        price_section := '<blockquote>🟢 السعر النهائي <b>⇚ ' || final_price || ' جنيه</b> (بدلاً من <s>' || old_price_val || ' جنيه</s>)</blockquote>' || chr(10) ||
                        '🔥 خصم ' || item.discount || '% ، ✨ وفر ' || item.extra_payment_discount || '% عند الدفع';
                    ELSIF (COALESCE(item.discount, 0) = 0 AND item.extra_payment_discount > 0) THEN
                        price_section := '<blockquote>🟢 السعر النهائي <b>⇚ ' || final_price || ' جنيه</b> (بدلاً من <s>' || FLOOR(item.price) || ' جنيه</s>)</blockquote>' || chr(10) ||
                        '✨ وفر ' || item.extra_payment_discount || '% عند الدفع';
                    ELSIF (item.discount > 0) THEN
                        price_section := '<blockquote>🟢 السعر النهائي <b>⇚ ' || final_price || ' جنيه</b> (بدلاً من <s>' || old_price_val || ' جنيه</s>)</blockquote>' || chr(10) ||
                        '🔥 خصم ' || item.discount || '%';
                    ELSE
                        price_section := '<blockquote>🟢 السعر <b>⇚ ' || final_price || ' جنيه</b></blockquote>';
                    END IF;
                    final_text := '<b>' || COALESCE(item.title, 'منتج') || '</b>' || chr(10) || chr(10) || price_section || chr(10) || chr(10) || '🔗 لينك المنتج:' || chr(10) || item.affiliate_link;
            END CASE;

            IF item.footer_text IS NOT NULL THEN
                final_text := final_text || chr(10) || chr(10) || item.footer_text;
            END IF;
        END IF;

        final_text := final_text || chr(10) || chr(10) || '🕒 آخر تحديث: ' || time_part || ' | #ad';
        fb_clean_text := regexp_replace(final_text, '<[^>]*>', '', 'g');

        BEGIN
            SELECT content::jsonb INTO tg_result FROM http_post(
                ('https://api.telegram.org/bot' || real_tg_token || '/sendPhoto')::text,
                jsonb_build_object('chat_id', set.tg_chat_id, 'photo', final_image_url, 'caption', final_text, 'parse_mode', 'HTML', 'disable_notification', COALESCE(item.disable_notification, false))::text,
                'application/json'
            );
            IF tg_result->>'ok' = 'true' THEN v_tg_msg_id := (tg_result->'result'->>'message_id')::int8; END IF;
        EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'Telegram Post Failed'; END;

        IF set.fb_page_id IS NOT NULL AND set.fb_page_id <> '' THEN
            BEGIN
                SELECT content::jsonb INTO fb_result FROM http_post(
                    ('https://graph.facebook.com/v19.0/' || set.fb_page_id || '/photos')::text,
                    jsonb_build_object('url', final_image_url, 'message', fb_clean_text, 'access_token', real_fb_token)::text,
                    'application/json'
                );
                IF fb_result IS NOT NULL AND fb_result->>'id' IS NOT NULL THEN v_fb_post_id := set.fb_page_id || '_' || (fb_result->>'id'); END IF;
            EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'Facebook Post Failed'; END;
        END IF;

        UPDATE products
        SET 
            published_at = (NOW() AT TIME ZONE 'Africa/Cairo')::text,
            scheduled_at = NULL,
            message_id = COALESCE(v_tg_msg_id, message_id),
            fb_post_id = COALESCE(v_fb_post_id, fb_post_id),
            last_update = (NOW() AT TIME ZONE 'Africa/Cairo')
        WHERE asin = item.asin;

    END LOOP;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION public.trigger_update_products()
RETURNS void AS $$
BEGIN
    PERFORM net.http_post(
        url := 'https://{{PROJECT_URL}}/functions/v1/update-products',
        headers := '{"Content-Type": "application/json"}'::jsonb,
        body := '{}'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.trigger_clean_products()
RETURNS void AS $$
BEGIN
    PERFORM net.http_post(
        url := 'https://{{PROJECT_URL}}/functions/v1/clean-products',
        headers := '{"Content-Type": "application/json"}'::jsonb,
        body := '{}'::jsonb
    );
END;
$$ LANGUAGE plpgsql;


DO $$ 
BEGIN
    PERFORM cron.unschedule(jobname) FROM cron.job WHERE jobname IN ('update-products', 'clean-products', 'auto-post-job');
EXCEPTION WHEN OTHERS THEN 
    RAISE NOTICE 'No jobs to unschedule';
END $$;

SELECT cron.schedule('update-products', '*/10 * * * *', 'SELECT public.trigger_update_products();');
SELECT cron.schedule('clean-products', '0 */6 * * *', 'SELECT public.trigger_clean_products();');
SELECT cron.schedule('auto-post-job', '* * * * *', 'SELECT handle_scheduled_publishing();');

ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon full access settings" ON public.user_settings;
CREATE POLICY "Allow anon full access settings" ON public.user_settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access products" ON public.products;
CREATE POLICY "Allow anon full access products" ON public.products FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER FUNCTION handle_scheduled_publishing() SECURITY DEFINER;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA public TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;